/**
 * ⚠️  DO NOT EDIT THIS FILE to change services.
 *
 * Service names and descriptions live in `src/lib/site-content.ts`.
 * This file just re-exports them so existing imports keep working.
 */
import { content } from "@/lib/site-content";
export type { Service } from "@/lib/site-content";

export const services = content.services;
export const pillars = content.pillars;
