/**
 * ⚠️  DO NOT EDIT THIS FILE to change wording or links.
 *
 * All editable content lives in `src/lib/site-content.ts`.
 * This file just re-shapes that content for the components and is kept so
 * existing imports keep working.
 */
import { content } from "@/lib/site-content";

export const site = {
  name: content.firm.name,
  legalName: content.firm.legalName,
  companyNumber: content.firm.companyNumber,
  tagline: content.home.hero.heading,
  shortDescription: content.seo.description,
  url: content.seo.url,
  heritage: content.heritage,
  address: content.address,
  contact: content.contact,
  hours: content.hours,
  credentials: content.footerCredentials,
};

export const nav = content.nav;

/** "Open in Google Maps" / directions link. Edit in site-content.ts → maps. */
export const mapsSearchUrl = content.maps.googleMapsDirectionsUrl;

/** The embedded map's source URL. Edit in site-content.ts → maps. */
export const mapsEmbedUrl = content.maps.googleMapsEmbedUrl;
